version: "3"
services:
  magento:
    build: 
      context: "./magento"
    ports:
      - "${MAGENTO_HTTP_PORT}:80"
    volumes:
      - "${APP_CODE_PATH_HOST}:/var/www/html/app/design/frontend/mytheme/default"
  mysql:
    image: "deckapp/mysql:v${AMYSQL_VERSION}"
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    volumes:
      - "${DATA_PATH_HOST}/mysql:/var/lib/mysql"
      - "${MYSQL_PATH}:/etc/mysql/"
    ports:
      - "${AMYSQL_PORT}:3306"
volumes: {}
