version: "3"
services:
  magento:
    image: "alexcheng/magento2:latest"
    ports:
      - "${MAGENTO_HTTP_PORT}:80"
    volumes:
      - "${APP_CODE_PATH_HOST}:/var/www/html/app/design/frontend/mytheme/default"
  mysql:
    image: "deckapp/mysql:v10.1.19"
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    volumes:
      - "${DATA_PATH_HOST}/mysql:/var/lib/mysql"
      - "./mysql:/etc/mysql/"
    ports:
      - "${MYSQL_PORT}:3306"
volumes: {}
