name: Magento 

on:
  schedule:
  - cron:  '30 02 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Magento-mariadb-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Magento, phpmyadmin, mariadb and elasticsearch
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        XDEBUG: true
        DISPLAY_PHPERROR: true
        APP_CODE_PATH_HOST: /tmp/magento
        DATA_PATH_HOST: /tmp/db
        hostname: magento
    - name: Container check
      run:  docker ps
    - name: Pre-defined file download
      run: docker exec magento_magento_1 wget -O /install.sh https://raw.githubusercontent.com/nabad600/image-test-file/main/install.sh
    - name: Host Name check
      run: docker exec magento_magento_1 hostname
    
    - name: PHP version check
      run: docker exec magento_magento_1 php -v
    - name: Mysql Driver check
      run: docker exec magento_magento_1 php -m | grep mysql
    - name: Git Version check
      run: docker exec magento_magento_1 git --version
    - name: Curl Version check
      run: docker exec magento_magento_1 curl --version
    - name: Nodejs Version check
      run: docker exec magento_magento_1 node --version
    - name: NPM Version check
      run: docker exec magento_magento_1 npm --version
    - name: Composer test
      run: docker exec magento_magento_1 composer
    - name: Container log check
      run: docker logs magento_magento_1
    - name: Pre-defined2 file download
      run: |
          sleep 90s
          docker exec magento_magento_1 wget -O /var/www/app/etc/env.php https://raw.githubusercontent.com/nabad600/image-test-file/main/env.php
          docker exec magento_magento_1 wget -O /var/www/app/env.php https://raw.githubusercontent.com/nabad600/image-test-file/main/app.env
    - name: Check Magento install or not
      run:  |
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:53487/index.php)" != "200" ]]; 
        do 
          sleep 50s
        done
    - name: Magento tset
      run: curl -i http://localhost:53487/
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker system prune -a
        sudo rm -rf /tmp/magento
        sudo rm -rf /tmp/db
    - name: Create ENV
      env:
        ENV_TEST: ${{ secrets.ENV_TEST }}
      run: |
        echo "$ENV_TEST" > .env.test
      shell: bash
    - name: Notify on SUCCESS
      if: ${{ SUCCESS() }}
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }}
        notification_title: "{emoji} *{job}* has {status_message}"
        message_format: "*{workflow}* {status_message} in <{branch_url}|{branch}> Architecture <{run_url}|{job}> Approved by ${{ github.event.head_commit.author.name }}"
        footer: "Linked Repo <{repo_url}|{repo}>" 
        mention_users: "D056LFW47NF,"
        mention_users_when: "SUCCESS"
        mention_groups: "C06H0SB11JL"
        mention_groups_when: "SUCCESS"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SUCCESS }}
    - name: Notify on FAIL
      if: ${{ failure() }}
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }}
        notification_title: "{emoji} *{job}* has {status_message}"
        message_format: "*{workflow}* {status_message} in <{branch_url}|{branch}> Architecture <{run_url}|{job}> Approved by ${{ github.event.head_commit.author.name }}"
        footer: "Linked Repo <{repo_url}|{repo}>"
        mention_users: "D056LFW47NF"
        mention_users_when: "failure,warnings"
        mention_groups: "C06G95T1YH3"
        mention_groups_when: "failure,warnings"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FAIL }}
  Magento-mariadb-ARM64:
    runs-on: ubuntu-22.04
    name: Magento-mariadb-ARM64
    steps:
    - uses: actions/checkout@v4
    - uses: uraimo/run-on-arch-action@v2
      name: Run commands
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu22.04
        run: |
          uname -a
          echo ::set-output name=uname::$(uname -a)

    - name: Get the output
      run: |
        echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
    - name: Build the Docker image Magento, phpmyadmin, mariadb and elasticsearch
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        XDEBUG: true
        DISPLAY_PHPERROR: true
        APP_CODE_PATH_HOST: /tmp/magento
        DATA_PATH_HOST: /tmp/db
        hostname: magento
    - name: Container check
      run:  docker ps
    - name: Pre-defined file download
      run: docker exec magento_magento_1 wget -O /install.sh https://raw.githubusercontent.com/nabad600/image-test-file/main/install.sh
    - name: Host Name check
      run: docker exec magento_magento_1 hostname
    
    - name: PHP version check
      run: docker exec magento_magento_1 php -v
    - name: Mysql Driver check
      run: docker exec magento_magento_1 php -m | grep mysql
    - name: Git Version check
      run: docker exec magento_magento_1 git --version
    - name: Curl Version check
      run: docker exec magento_magento_1 curl --version
    - name: Nodejs Version check
      run: docker exec magento_magento_1 node --version
    - name: NPM Version check
      run: docker exec magento_magento_1 npm --version
    - name: Composer test
      run: docker exec magento_magento_1 composer
    - name: Container log check
      run: docker logs magento_magento_1
    - name: Pre-defined2 file download
      run: |
          sleep 90s
          docker exec magento_magento_1 wget -O /var/www/app/etc/env.php https://raw.githubusercontent.com/nabad600/image-test-file/main/env.php
          docker exec magento_magento_1 wget -O /var/www/app/env.php https://raw.githubusercontent.com/nabad600/image-test-file/main/app.env
    - name: Check Magento install or not
      run:  |
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:53487/index.php)" != "200" ]]; 
        do 
          sleep 50s
        done
    - name: Magento tset
      run: curl -i http://localhost:53487/
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker system prune -a
        sudo rm -rf /tmp/magento
        sudo rm -rf /tmp/db
    - name: Create ENV
      env:
        ENV_TEST: ${{ secrets.ENV_TEST }}
      run: |
        echo "$ENV_TEST" > .env.test
      shell: bash
    - name: Notify on SUCCESS
      if: ${{ SUCCESS() }}
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }}
        notification_title: "{emoji} *{job}* has {status_message}"
        message_format: "*{workflow}* {status_message} in <{branch_url}|{branch}> Architecture <{run_url}|{job}> Approved by ${{ github.event.head_commit.author.name }}"
        footer: "Linked Repo <{repo_url}|{repo}>" 
        mention_users: "D056LFW47NF,"
        mention_users_when: "SUCCESS"
        mention_groups: "C06H0SB11JL"
        mention_groups_when: "SUCCESS"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SUCCESS }}
    - name: Notify on FAIL
      if: ${{ failure() }}
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }}
        notification_title: "{emoji} *{job}* has {status_message}"
        message_format: "*{workflow}* {status_message} in <{branch_url}|{branch}> Architecture <{run_url}|{job}> Approved by ${{ github.event.head_commit.author.name }}"
        footer: "Linked Repo <{repo_url}|{repo}>"
        mention_users: "D056LFW47NF"
        mention_users_when: "failure,warnings"
        mention_groups: "C06G95T1YH3"
        mention_groups_when: "failure,warnings"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FAIL }}
  
