name: Magento 

on:
  schedule:
  - cron:  '30 1 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Magento-mariadb-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Magento, phpmyadmin, mariadb and elasticsearch
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        PHP_VERSION: "7.4"
        XDEBUG: true
        DISPLAY_PHPERROR: true
        APP_CODE_PATH_HOST: /tmp/magento
        hostname: magento
    - name: Container check
      run:  docker ps
    # - name: PHP version check
    #   run: docker exec magento_magento_1 php -v
    # - name: Mysql Driver check
    #   run: docker exec magento_magento_1 php -m | grep mysql
    # - name: Git Version check
    #   run: docker exec magento_magento_1 git --version
    # - name: Curl Version check
    #   run: docker exec magento_magento_1 curl --version
    # - name: Nodejs Version check
    #   run: docker exec magento_magento_1 node --version
    # - name: NPM Version check
    #   run: docker exec magento_magento_1 npm --version
    # - name: Composer test
    #   run: docker exec magento_magento_1 composer
    # - name: Container log check
    #   run: docker logs magento_magento_1
    # - name: Check Magento install or not
    #   run:  |
    #     while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:53487/index.php)" != "200" ]]; 
    #     do 
    #       sleep 50s
    #     done
    # - name: Destroy container and file
    #   run:  |
    #     docker-compose down
    #     docker stop $(docker ps -a -q)
    #     echo "y" | docker system prune -a
    #     sudo rm -rf /tmp/magento