name: Magento

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Magento
      run: docker-compose build
      env:
          PHP_VERSION: "7.4"
          XDEBUG: true
          DISPLAY_PHPERROR: true
